version: '3.2'

services:
  db:
    image: postgres:13.4-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - ".env"
  app:
    container_name: "nextcloud_app"
    image: nextcloud:22.1.1
    restart: always
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./app:/var/www/html
    env_file:
      - ".env"
    depends_on:
      - db

