version: "3"

networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:1.15.3-rootless
    container_name: gitea
    env_file:
      - ".env"
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    restart: always
    env_file:
      - ".env"
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
