version: "3"

services:
  bitwarden:
    image: "vaultwarden/server:1.23.0-alpine"
    restart: always
    env_file:
      - ".env"
    volumes:
      - "./bw_data:/data"
    ports:
      - "127.0.0.1:8080:80"

